### ISSUE TITLE
Error:Error: Command failed: /Users/hanjun/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build . Debug

### ISSUE THREAD

**Issue by hanjun0123** [yuan-gao/zhihuDaily-Weex#1]
Error:Error: Command failed: /Users/hanjun/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build . Debug
/bin/sh: /Users/hanjun/.xtoolkit/node_modules/weexpack/lib/build/lib/cocoapods-build: No such file or directory

    at checkExecSyncError (child_process.js:486:13)
    at Object.execSync (child_process.js:526:13)
    at _runAppOnDevice (/Users/hanjun/.xtoolkit/node_modules/weexpack/lib/run/ios.js:498:20)
    at /Users/hanjun/.xtoolkit/node_modules/weexpack/lib/run/ios.js:375:7
    at runApp (/Users/hanjun/.xtoolkit/node_modules/weexpack/lib/run/ios.js:371:10)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by yuan-gao** [comment]
跑iOS的话  需要给Mac装cocoapods

**Comment by hanjun0123** [comment]
pod --version
1.4.0
装了

**Comment by yuan-gao** [comment]
那你cd到ios目录 执行`pod install`

**Comment by hanjun0123** [comment]
![image](https://user-images.githubusercontent.com/5164435/37186949-e67e2130-2382-11e8-97ad-0d12be0b6fc5.png)
